# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pura Dawid
email: puradawid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming thoughts, best and even worst practices, software crafting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://puradawid.github.io" # the base hostname & protocol for your site
twitter_username: puradawid 
github_username:  puradawid

# Build settings
markdown: kramdown
