# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Engineering Blog - Pura Dawid
short_title: Pura Dawid's Blog
email: puradawid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about software engineering and programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://puradawid.pro" # the base hostname & protocol for your site
twitter_username: puradawid 
github_username:  puradawid
excerpt_separator: "<!-- more -->"
permalink: /:categories/:title:output_ext

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
